### ISSUE TITLE
Timeout from POI Api

### ISSUE THREAD

**Issue by pnancke** [pnancke/trip-planner#40]
Timeout from POI Api if the start and destination are too far away (eg. Leipzig - Paris)

```
startLon: 12.3810549
startLat: 51.3391827
endLon: 2.3514992
endLat: 48.8566101
```

Stacktrace:
```
runtime error: Query timed out in "print" at line 15 after 195 seconds. . Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException:  runtime error: Query timed out in "print" at line 15 after 195 seconds. 
	at trip.planner.POIParser.parse(POIParser.groovy:38)
	at trip.planner.HomeController$$EPmtqIBs.getRoute(HomeController.groovy:31)
	... 3 common frames omitted

```

this problem should be solved with #57

**Comment by pnancke** [comment]
related to #33
