### ISSUE TITLE
Fix Start - Destination Swap

### ISSUE THREAD

**Issue by MZober1993** [pnancke/trip-planner#60]
Error by typing 
Start: Leipzig, Leipzig Deutschland
Destination: Halle (Saale), Halle (Saale) Deutschland

`ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalArgumentException occurred when processing request: [GET] /home/getRoute - parameters:
start: Leipzig, Leipzig Deutschland
destination: Halle (Saale), Halle (Saale) Deutschland
additionalTravelTime: 1800
lang: de
False query input parameter: The value of attribute "n" of the element "bbox-query" must always be greater or equal than the value of attribute "s".. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: False query input parameter: The value of attribute "n" of the element "bbox-query" must always be greater or equal than the value of attribute "s".
	at trip.planner.POIParser.parse(POIParser.groovy:31)
	at trip.planner.HomeController$$EPnnNQxM.getPOIs(HomeController.groovy:100)
	at trip.planner.HomeController$$EPnnNQxM.getRoute(HomeController.groovy:41)
	... 3 common frames omitted
`

**Comment by pnancke** [comment]
may be obsolet when #62 is merged.
