### ISSUE TITLE
Fix Nullpointer by getRoute in HomeController

### ISSUE THREAD

**Issue by MZober1993** [pnancke/trip-planner#63]
Error Message:

`ERROR org.grails.web.errors.GrailsExceptionResolver - NoSupportedDataTypeException occurred when processing request: [GET] /home/getRoute - parameters:
start: Leipzig
destination: Dresden
additionalTravelTime: 1800
lang: de
No data type found satisfying: NumberVector,field AND NumberVector,dim=2
Available types: DBID DoubleVector,field,mindim=2147483647,maxdim=0. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: de.lmu.ifi.dbs.elki.data.type.NoSupportedDataTypeException: No data type found satisfying: NumberVector,field AND NumberVector,dim=2
Available types: DBID DoubleVector,field,mindim=2147483647,maxdim=0
        at de.lmu.ifi.dbs.elki.database.AbstractDatabase.getRelation(AbstractDatabase.java:126)
        at de.lmu.ifi.dbs.elki.algorithm.AbstractAlgorithm.run(AbstractAlgorithm.java:81)
        at de.lmu.ifi.dbs.elki.algorithm.clustering.kmeans.AbstractKMeans.run(AbstractKMeans.java:73)
        at trip.planner.osm.api.ElkiWrapper.extractClusters(ElkiWrapper.groovy:27)
        at trip.planner.util.ClusterHelper.extractCoordinateClusterWithoutOutliers(ClusterHelper.groovy:73)
        at trip.planner.HomeController.getPOIs(HomeController.groovy:105)
        at trip.planner.HomeController.getRoute(HomeController.groovy:47)
        ... 3 common frames omitted
`

**Comment by pnancke** [comment]
Additional Info, this happens when the routing api does not responds

**Comment by MZober1993** [comment]
This happens also when the size of the POI-List is empty. 

The method getPois(..) should return an empty List then.
When this method returns an empty List of Pois an allert occures (no such route...).
I think this behaviour can be replaced with the drawing of the shourtest Path and maybe with a ui-componant that shows the count of all given pois (because this allert pop-up sucks).
